const trainDetectionData = [
    // Train 992 - Aluthgama Detection Records
    { date: '2025-04-01', day: 'Wed', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:02 AM', minutesDeviationKollupitiya: 2, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:05 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-02', day: 'Thu', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:10 AM', minutesDeviationKollupitiya: 10, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:14 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-03', day: 'Fri', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:03 AM', minutesDeviationKollupitiya: 3, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:08 AM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-04', day: 'Sat', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:01 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:05 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-05', day: 'Sun', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:04 AM', minutesDeviationKollupitiya: 4, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:08 AM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-06', day: 'Mon', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:02 AM', minutesDeviationKollupitiya: 2, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:08 AM', minutesDeviationNextStation: 6, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-07', day: 'Tue', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:00 AM', minutesDeviationKollupitiya: 0, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:05 AM', minutesDeviationNextStation: 6, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-08', day: 'Wed', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:03 AM', minutesDeviationKollupitiya: 3, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:04 AM', minutesDeviationNextStation: 1, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-09', day: 'Thu', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:01 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:08 AM', minutesDeviationNextStation: 7, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-10', day: 'Fri', trainNumber: '992', trainName: 'Aluthgama', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:00 AM', actualKollupitiya: '6:34 AM', minutesDeviationKollupitiya: 35, nextStationTime: 'Kompannavidiya', actualNextStationTime: '6:37 AM', minutesDeviationNextStation: 2, notes: 'Sample record - replace/edit if needed' },

    // Train 16311 - Wadduwa Passenger Detection Records
    { date: '2025-04-01', day: 'Wed', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:52 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Bambalapitiya', actualNextStationTime: '4:56 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-02', day: 'Thu', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:54 AM', minutesDeviationKollupitiya: 3, nextStationTime: 'Bambalapitiya', actualNextStationTime: '4:59 AM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-03', day: 'Fri', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:51 AM', minutesDeviationKollupitiya: 0, nextStationTime: 'Bambalapitiya', actualNextStationTime: '4:55 AM', minutesDeviationNextStation: 3, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-04', day: 'Sat', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:53 AM', minutesDeviationKollupitiya: 2, nextStationTime: 'Bambalapitiya', actualNextStationTime: '4:57 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-05', day: 'Sun', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:55 AM', minutesDeviationKollupitiya: 4, nextStationTime: 'Bambalapitiya', actualNextStationTime: '5:01 AM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-06', day: 'Mon', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:52 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Bambalapitiya', actualNextStationTime: '5:01 AM', minutesDeviationNextStation: 9, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-07', day: 'Tue', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:54 AM', minutesDeviationKollupitiya: 3, nextStationTime: 'Bambalapitiya', actualNextStationTime: '5:01 AM', minutesDeviationNextStation: 7, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-08', day: 'Wed', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:51 AM', minutesDeviationKollupitiya: 0, nextStationTime: 'Bambalapitiya', actualNextStationTime: '5:01 AM', minutesDeviationNextStation: 10, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-09', day: 'Thu', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:53 AM', minutesDeviationKollupitiya: 2, nextStationTime: 'Bambalapitiya', actualNextStationTime: '5:01 AM', minutesDeviationNextStation: 8, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-10', day: 'Fri', trainNumber: '16311', trainName: 'Wadduwa Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '4:51 AM', actualKollupitiya: '4:55 AM', minutesDeviationKollupitiya: 4, nextStationTime: 'Bambalapitiya', actualNextStationTime: '5:01 AM', minutesDeviationNextStation: 6, notes: 'Sample record - replace/edit if needed' },

    // Train 851 - Galle Passenger Detection Records
    { date: '2025-04-01', day: 'Wed', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:10 PM', minutesDeviationKollupitiya: 4, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:14 PM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-02', day: 'Thu', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:08 PM', minutesDeviationKollupitiya: 2, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:13 PM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-03', day: 'Fri', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:12 PM', minutesDeviationKollupitiya: 6, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:16 PM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-04', day: 'Sat', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:06 PM', minutesDeviationKollupitiya: 0, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:15 PM', minutesDeviationNextStation: 9, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-05', day: 'Sun', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:11 PM', minutesDeviationKollupitiya: 5, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:16 PM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-06', day: 'Mon', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:06 PM', minutesDeviationKollupitiya: 0, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:14 PM', minutesDeviationNextStation: 8, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-07', day: 'Tue', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:08 PM', minutesDeviationKollupitiya: 2, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:13 PM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-08', day: 'Wed', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:12 PM', minutesDeviationKollupitiya: 6, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:16 PM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-09', day: 'Thu', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:09 PM', minutesDeviationKollupitiya: 3, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:15 PM', minutesDeviationNextStation: 6, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-10', day: 'Fri', trainNumber: '851', trainName: 'Galle Passenger', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '6:06 PM', actualKollupitiya: '6:11 PM', minutesDeviationKollupitiya: 5, nextStationTime: 'Bambalapitiya', actualNextStationTime: '6:16 PM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },

    // Train 827 - Morning Fort Passenger Detection Records
    { date: '2025-04-01', day: 'Wed', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:31 AM', minutesDeviationKollupitiya: 3, nextStationTime: 'Kompannavidiya', actualNextStationTime: '8:35 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-02', day: 'Thu', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:29 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Kompannavidiya', actualNextStationTime: '8:33 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-03', day: 'Fri', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:32 AM', minutesDeviationKollupitiya: 4, nextStationTime: 'Kompannavidiya', actualNextStationTime: '8:37 AM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-04', day: 'Sat', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:30 AM', minutesDeviationKollupitiya: 2, nextStationTime: 'Kompannavidiya', actualNextStationTime: '8:34 AM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-05', day: 'Sun', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:28 AM', minutesDeviationKollupitiya: 60, nextStationTime: 'Kompannavidiya', actualNextStationTime: '9:31 AM', minutesDeviationNextStation: 3, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-06', day: 'Mon', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:31 AM', minutesDeviationKollupitiya: 3, nextStationTime: 'Kompannavidiya', actualNextStationTime: '8:35 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-07', day: 'Tue', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:29 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Kompannavidiya', actualNextStationTime: '8:33 AM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-08', day: 'Wed', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:52 AM', minutesDeviationKollupitiya: 24, nextStationTime: 'Kompannavidiya', actualNextStationTime: '8:57 AM', minutesDeviationNextStation: 5, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-09', day: 'Thu', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:30 AM', minutesDeviationKollupitiya: 2, nextStationTime: 'Kompannavidiya', actualNextStationTime: '8:34 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-10', day: 'Fri', trainNumber: '827', trainName: 'Morning Fort Passenger', direction: 'UP', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Slow', scheduledKollupitiya: '8:28 AM', actualKollupitiya: '8:28 AM', minutesDeviationKollupitiya: 0, nextStationTime: 'Kompannavidiya', actualNextStationTime: '8:35 AM', minutesDeviationNextStation: 7, notes: 'Sample record - replace/edit if needed' },

    // Train 854 - Rajarata Rejini Detection Records
    { date: '2025-04-01', day: 'Wed', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:37 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:40 AM', minutesDeviationNextStation: 3, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-02', day: 'Thu', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:36 AM', minutesDeviationKollupitiya: 0, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:39 AM', minutesDeviationNextStation: 3, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-03', day: 'Fri', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:38 AM', minutesDeviationKollupitiya: 2, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:42 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-04', day: 'Sat', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:37 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:40 AM', minutesDeviationNextStation: 3, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-05', day: 'Sun', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:39 AM', minutesDeviationKollupitiya: 3, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:42 AM', minutesDeviationNextStation: 3, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-06', day: 'Mon', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:37 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:40 AM', minutesDeviationNextStation: 3, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-07', day: 'Tue', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:38 AM', minutesDeviationKollupitiya: 2, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:39 AM', minutesDeviationNextStation: 0, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-08', day: 'Wed', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:38 AM', minutesDeviationKollupitiya: 2, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:42 AM', minutesDeviationNextStation: 4, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-09', day: 'Thu', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:37 AM', minutesDeviationKollupitiya: 1, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:40 AM', minutesDeviationNextStation: 3, notes: 'Sample record - replace/edit if needed' },
    { date: '2025-04-10', day: 'Fri', trainNumber: '854', trainName: 'Rajarata Rejini', direction: 'DOWN', line: 'Coastal Line', nextStation: 'Kollupitiya', trainType: 'Express', scheduledKollupitiya: '10:36 AM', actualKollupitiya: '10:39 AM', minutesDeviationKollupitiya: 3, nextStationTime: 'Bambalapitiya', actualNextStationTime: '10:42 AM', minutesDeviationNextStation: 3, notes: 'Sample record - replace/edit if needed' }
];

module.exports = trainDetectionData;
